app = "hashify"
primary_region = "ord"

[deploy]
  strategy = "bluegreen"

[env]
  LOG_LEVEL = "debug"
  LISTEN_HTTP = "0.0.0.0:8080"
  LISTEN_HTTP_METRICS = "0.0.0.0:9091"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 400
    hard_limit = 500

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/status"

[metrics]
  port = 9091
  path = "/metrics"