// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package openapi

// Defines values for DigestAlgorithms.
const (
	Blake2b256     DigestAlgorithms = "Blake2b-256"
	Blake2b384     DigestAlgorithms = "Blake2b-384"
	Blake2b512     DigestAlgorithms = "Blake2b-512"
	Blake2s128     DigestAlgorithms = "Blake2s-128"
	Blake2s256     DigestAlgorithms = "Blake2s-256"
	HighwayHash128 DigestAlgorithms = "HighwayHash-128"
	HighwayHash256 DigestAlgorithms = "HighwayHash-256"
	HighwayHash64  DigestAlgorithms = "HighwayHash-64"
	MD4            DigestAlgorithms = "MD4"
	MD5            DigestAlgorithms = "MD5"
	SHA1           DigestAlgorithms = "SHA1"
	SHA256         DigestAlgorithms = "SHA256"
	SHA3256        DigestAlgorithms = "SHA3-256"
	SHA3384        DigestAlgorithms = "SHA3-384"
	SHA3512        DigestAlgorithms = "SHA3-512"
	SHA384         DigestAlgorithms = "SHA384"
	SHA512         DigestAlgorithms = "SHA512"
	SHA512256      DigestAlgorithms = "SHA512-256"
)

// Defines values for DigestFormats.
const (
	Base32    DigestFormats = "base32"
	Base64    DigestFormats = "base64"
	Base64url DigestFormats = "base64url"
	Hex       DigestFormats = "hex"
)

// DigestAlgorithms defines model for DigestAlgorithms.
type DigestAlgorithms string

// DigestFormats Hash digest encoding format
type DigestFormats string

// ErrorResponseContent defines model for ErrorResponseContent.
type ErrorResponseContent struct {
	// Error Error message
	Error *string `json:"Error,omitempty"`
}

// SuccessResponseContent defines model for SuccessResponseContent.
type SuccessResponseContent struct {
	// Digest Hash Digest in the format requested, matching DigestEnc
	Digest *string `json:"Digest,omitempty"`

	// DigestEnc Hash digest encoding format
	DigestEnc *DigestFormats `json:"DigestEnc,omitempty"`

	// Key Hex format key used for Hashing
	Key  *string           `json:"Key,omitempty"`
	Type *DigestAlgorithms `json:"Type,omitempty"`
}

// GetHashAlgorithmDigestFormatParams defines parameters for GetHashAlgorithmDigestFormat.
type GetHashAlgorithmDigestFormatParams struct {
	Value string `form:"value" json:"value"`

	// Key Hex format key used for Hashing
	Key *string `form:"key,omitempty" json:"key,omitempty"`

	// XHashifyKey Hex format key used for Hashing
	XHashifyKey *string `json:"x-hashify-key,omitempty"`
}
