// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Hash Digest of Input using given algorithm and digest encoding format
	// (GET /hash/{algorithm}/{digestFormat})
	GetHashAlgorithmDigestFormat(ctx echo.Context, algorithm HashAlgorithmName, digestFormat DigestFormats, params GetHashAlgorithmDigestFormatParams) error
	// Hash Key Generator
	// (GET /keygen/{keyLength})
	GetKeygenKeyLength(ctx echo.Context, keyLength int) error
	// List Hashing Algorithms
	// (GET /methods)
	GetMethods(ctx echo.Context) error
	// Status Check
	// (GET /status)
	GetStatus(ctx echo.Context) error
	// Get API Version
	// (GET /version)
	GetVersion(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetHashAlgorithmDigestFormat converts echo context to params.
func (w *ServerInterfaceWrapper) GetHashAlgorithmDigestFormat(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "algorithm" -------------
	var algorithm HashAlgorithmName

	err = runtime.BindStyledParameterWithLocation("simple", false, "algorithm", runtime.ParamLocationPath, ctx.Param("algorithm"), &algorithm)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter algorithm: %s", err))
	}

	// ------------- Path parameter "digestFormat" -------------
	var digestFormat DigestFormats

	err = runtime.BindStyledParameterWithLocation("simple", false, "digestFormat", runtime.ParamLocationPath, ctx.Param("digestFormat"), &digestFormat)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter digestFormat: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHashAlgorithmDigestFormatParams
	// ------------- Required query parameter "value" -------------

	err = runtime.BindQueryParameter("form", true, true, "value", ctx.QueryParams(), &params.Value)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter value: %s", err))
	}

	// ------------- Optional query parameter "key" -------------

	err = runtime.BindQueryParameter("form", true, false, "key", ctx.QueryParams(), &params.Key)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetHashAlgorithmDigestFormat(ctx, algorithm, digestFormat, params)
	return err
}

// GetKeygenKeyLength converts echo context to params.
func (w *ServerInterfaceWrapper) GetKeygenKeyLength(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "keyLength" -------------
	var keyLength int

	err = runtime.BindStyledParameterWithLocation("simple", false, "keyLength", runtime.ParamLocationPath, ctx.Param("keyLength"), &keyLength)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter keyLength: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetKeygenKeyLength(ctx, keyLength)
	return err
}

// GetMethods converts echo context to params.
func (w *ServerInterfaceWrapper) GetMethods(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetMethods(ctx)
	return err
}

// GetStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetStatus(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetStatus(ctx)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/hash/:algorithm/:digestFormat", wrapper.GetHashAlgorithmDigestFormat)
	router.GET(baseURL+"/keygen/:keyLength", wrapper.GetKeygenKeyLength)
	router.GET(baseURL+"/methods", wrapper.GetMethods)
	router.GET(baseURL+"/status", wrapper.GetStatus)
	router.GET(baseURL+"/version", wrapper.GetVersion)

}

type GetHashAlgorithmDigestFormatRequestObject struct {
	Algorithm    HashAlgorithmName `json:"algorithm"`
	DigestFormat DigestFormats     `json:"digestFormat"`
	Params       GetHashAlgorithmDigestFormatParams
}

type GetHashAlgorithmDigestFormatResponseObject interface {
	VisitGetHashAlgorithmDigestFormatResponse(w http.ResponseWriter) error
}

type GetHashAlgorithmDigestFormat200JSONResponse SuccessResponseContent

func (response GetHashAlgorithmDigestFormat200JSONResponse) VisitGetHashAlgorithmDigestFormatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHashAlgorithmDigestFormat400JSONResponse ErrorResponseContent

func (response GetHashAlgorithmDigestFormat400JSONResponse) VisitGetHashAlgorithmDigestFormatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetHashAlgorithmDigestFormat404JSONResponse ErrorResponseContent

func (response GetHashAlgorithmDigestFormat404JSONResponse) VisitGetHashAlgorithmDigestFormatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetHashAlgorithmDigestFormat500JSONResponse ErrorResponseContent

func (response GetHashAlgorithmDigestFormat500JSONResponse) VisitGetHashAlgorithmDigestFormatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetKeygenKeyLengthRequestObject struct {
	KeyLength int `json:"keyLength"`
}

type GetKeygenKeyLengthResponseObject interface {
	VisitGetKeygenKeyLengthResponse(w http.ResponseWriter) error
}

type GetKeygenKeyLength200JSONResponse struct {
	// KeyHex Hex format key
	KeyHex string `json:"KeyHex"`

	// Length Length of key in bytes
	Length int `json:"Length"`
}

func (response GetKeygenKeyLength200JSONResponse) VisitGetKeygenKeyLengthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetKeygenKeyLength400JSONResponse ErrorResponseContent

func (response GetKeygenKeyLength400JSONResponse) VisitGetKeygenKeyLengthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetKeygenKeyLength500JSONResponse ErrorResponseContent

func (response GetKeygenKeyLength500JSONResponse) VisitGetKeygenKeyLengthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMethodsRequestObject struct {
}

type GetMethodsResponseObject interface {
	VisitGetMethodsResponse(w http.ResponseWriter) error
}

type GetMethods200ResponseHeaders struct {
	ContentType string
}

type GetMethods200JSONResponse struct {
	Body    []HashAlgorithm
	Headers GetMethods200ResponseHeaders
}

func (response GetMethods200JSONResponse) VisitGetMethodsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", fmt.Sprint(response.Headers.ContentType))
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetStatusRequestObject struct {
}

type GetStatusResponseObject interface {
	VisitGetStatusResponse(w http.ResponseWriter) error
}

type GetStatus200JSONResponse struct {
	HashesGenerated int64  `json:"hashesGenerated"`
	KeysGenerated   int64  `json:"keysGenerated"`
	Status          string `json:"status"`
	Uptime          string `json:"uptime"`
}

func (response GetStatus200JSONResponse) VisitGetStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse struct {
	Version string `json:"version"`
}

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get Hash Digest of Input using given algorithm and digest encoding format
	// (GET /hash/{algorithm}/{digestFormat})
	GetHashAlgorithmDigestFormat(ctx context.Context, request GetHashAlgorithmDigestFormatRequestObject) (GetHashAlgorithmDigestFormatResponseObject, error)
	// Hash Key Generator
	// (GET /keygen/{keyLength})
	GetKeygenKeyLength(ctx context.Context, request GetKeygenKeyLengthRequestObject) (GetKeygenKeyLengthResponseObject, error)
	// List Hashing Algorithms
	// (GET /methods)
	GetMethods(ctx context.Context, request GetMethodsRequestObject) (GetMethodsResponseObject, error)
	// Status Check
	// (GET /status)
	GetStatus(ctx context.Context, request GetStatusRequestObject) (GetStatusResponseObject, error)
	// Get API Version
	// (GET /version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetHashAlgorithmDigestFormat operation middleware
func (sh *strictHandler) GetHashAlgorithmDigestFormat(ctx echo.Context, algorithm HashAlgorithmName, digestFormat DigestFormats, params GetHashAlgorithmDigestFormatParams) error {
	var request GetHashAlgorithmDigestFormatRequestObject

	request.Algorithm = algorithm
	request.DigestFormat = digestFormat
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHashAlgorithmDigestFormat(ctx.Request().Context(), request.(GetHashAlgorithmDigestFormatRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHashAlgorithmDigestFormat")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHashAlgorithmDigestFormatResponseObject); ok {
		return validResponse.VisitGetHashAlgorithmDigestFormatResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// GetKeygenKeyLength operation middleware
func (sh *strictHandler) GetKeygenKeyLength(ctx echo.Context, keyLength int) error {
	var request GetKeygenKeyLengthRequestObject

	request.KeyLength = keyLength

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetKeygenKeyLength(ctx.Request().Context(), request.(GetKeygenKeyLengthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetKeygenKeyLength")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetKeygenKeyLengthResponseObject); ok {
		return validResponse.VisitGetKeygenKeyLengthResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// GetMethods operation middleware
func (sh *strictHandler) GetMethods(ctx echo.Context) error {
	var request GetMethodsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMethods(ctx.Request().Context(), request.(GetMethodsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMethods")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMethodsResponseObject); ok {
		return validResponse.VisitGetMethodsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// GetStatus operation middleware
func (sh *strictHandler) GetStatus(ctx echo.Context) error {
	var request GetStatusRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetStatus(ctx.Request().Context(), request.(GetStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetStatusResponseObject); ok {
		return validResponse.VisitGetStatusResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(ctx echo.Context) error {
	var request GetVersionRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx.Request().Context(), request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		return validResponse.VisitGetVersionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RYW2/juBX+KwRbYF7o2JIs34o+ZGYzkyDJtNhMd1ss8kBJxxbXEqUlKU8Ew/+9IHWx",
	"ZEtO7Em7bzZFHn48l+985Bb7SZwmHLiSeLHF0g8hpubnT2wFUn1OREyLbwFIX7BUsYTjBb6lMkSBmYOA",
	"+0nA+AotzWxMMPAsxovfsEclODYm5sdkXP/IRIQJDuEFPxMMLzROI8ALM0CwylP9RyrB+ArvCL4RIhE/",
	"g0wTLuFTwhVwpRGlIklBKAYGn5l1DNQMoxikpCvAzd3u+IZGLEC38IJ+oVEGGj9KqaAxKBDowxryDwTF",
	"mVQoFcmGBYDWkCMq0R8ZiLyYihKBQqCBXvDvgXYLW+aDe8g/HB9lV48k3u/gK304veI6WiWCqTDW8GuA",
	"v23xDQ/ShOnT4mFIZTj8+HB9f2N/HNjuBBP8SF/uIX8AvlIhXowIfmS8PfCVxnq7jxFdg+2ZZTtywq4z",
	"G19iVy87ade17Evs6mUn7MqBZc/Ot1ssO2n3Iv/Kfv/e3n25/fX6P6/bdOza6C1bhd9prhPkVcODyfhi",
	"25PxadNv8nGP7V5HP/50VqLp6T123PPsuN12nm6vrXMMmfl9ls7MnnJFn7Uza7Jc0WftzEosV5ywNjj/",
	"tNWq3hNfYNN5xeIFXhyc8qMzON+TxZrdMzlsXbX9Bv13Mn7ZYRc4E6yrVbbRNKyN6smMK1iBMLNbUF+b",
	"XZxji/8qYIkX+C/DvXYYlsJh2OpmZoFuegL+yJiAQEsCM0j2Rz5AcXCE59c6ZgWqUhzNTkda/Ym0ugpp",
	"9QLSYnBySI/kiNPIETsTXFKaIaSSTmouqMu4rsBW8TRyvpGsdcY8d0T6KfN9kPJVWVTouB4BV3xEjCMV",
	"QinfkI4WSAUBQTFVfqiVXTHxhvtdSbf/+Ep2tDXljuB7yDuQwUsFRcutTEJglJnRVnzVheCbGfjR1Cxd",
	"1TxQafo4DfVaxpeJ3tVPuKK+8TEvW2AhA9EXpsLMwwRrwbvAoVKpXAyHKzN85SfxMPjOuCl0tsyHAZN+",
	"JiVLuPFOxHzgEhp2H+++oYdy9K1GvSjxhjFlfPhw9+nm69ONNq2YippAr/95hwnegJBFDKyr0dVIT0xS",
	"4DRleIEdM0RwSlVoMqvgpy2tfLobboNGgHd6zgqMW3RCUh3euwAv8BdQrWA008JsUCpwaTRw83oQRcmv",
	"iYgCrJ2PF9jocEwq92y0isfNoCqRASmvNRrIkSA/P/n2eOzJzKYjy6Lu3Bk5DlDHCqauQ21v6QRWMJ3M",
	"YTr1fNee2q7t2HMKrmVRak1Hwdiaum7PKdag/5zEbJbpQOxX1WE4ef6zC6Rzr6AdsMu2OyAD3RVFSWYm",
	"vezRqCqukthomkbMN3k0/F3qcG3fuFcPWZoqbse/nIkqKLoGxu+IpPMu24HjIw0qIi4gjP/vEL4mCn1O",
	"Mh5oAO6f4IM7rkBwGqEnEBsQqLjh63kyi2Mq8oJLULOVJUt0x9NMoUzqvrViG+Corg1EedD3aqHtDteQ",
	"r4APt+tKgTRZrI3uC3BNaoDuIdfbUuExJajIUWRWoixFKkG2O0FerkBickyD92a7pvo5IL+O4ls3ZvdX",
	"XkxfWKwlke1OCI4ZL/5Zx8LuwsKraXCru/gtvOAFnvjTAFx3bM8mPg3mXmDNlt5oDtSbzMa2Q+dLi3q2",
	"587tmTcZwcwGx57O/ZkLlg3Lmabu/X1y1zxOW9NUG54m7xZXvwO0I9WxF85tGMW4zgndQhiv41/D0bfl",
	"WspXkSDnBK2tXEqH1JC69Uob5T/u385tjWCXz2z169mm5+WsQFK9n3mAPFDfATiyTBEWl7X/LWm6l56t",
	"eDNcFQWuKUJn07ujfQu9GWrTBFOyTaLTRNGVZgccwJJmkcLPhrpiUGESyF6++hmUYLABFLGCJ7V8Q4n5",
	"LJHRsIxLpFlGEgTl/UwSEy5W5DIHCCDoYrLHcvcfbOJMQSzPEip4/6hKhaB5T6oTXDzSGuNlUAbVtWG/",
	"/54wDnH+DfkhFRLU3//17fNg1vG4u2uH7kG7uZSNqIYre+MnFVWZPCWan4oZP+jiNpXqJABZ9bKg5YPp",
	"aD6Zu22mMrfhmpk63wnWkL+vwb1n9uExIT1i5CxVrHwPqGdO7XAcjydXU8d1RtbEtmTnw3yTTg+dcnim",
	"GlK941sIV5c58wFp4m1lShFX9CkEf13IkPoi1qs9lL6yoV/KeR0Fuf/0jtnSwLV3sFVeDE/7tFr6Jk8V",
	"InyZRQ0dfiT7mg4oas/waCGc2ndjmrKr8j58xUHh3fPuvwEAAP//3nM1dvsaAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
